# Generated by Django 2.2.1 on 2019-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='系统配置名称')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='EnvConfig',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('EnvName', models.CharField(max_length=50, verbose_name='测试环境名称')),
                ('EnvBaseUrl', models.CharField(max_length=50, verbose_name='被测服务基础Url')),
                ('EnvScheme', models.CharField(max_length=50, verbose_name='被测服务协议')),
                ('EnvPort', models.CharField(blank=True, max_length=8, verbose_name='被测服务端口号')),
                ('EnvTimeout', models.CharField(max_length=4, verbose_name='请求超时时间')),
                ('DatabaseHost', models.CharField(max_length=50, verbose_name='数据库服务器地址')),
                ('Database_Username', models.CharField(max_length=50, verbose_name='数据库用户名')),
                ('Database_Password', models.CharField(max_length=50, verbose_name='数据库密码')),
                ('Database_Port', models.CharField(max_length=50, verbose_name='数据库端口号')),
                ('Database_Database', models.CharField(max_length=50, verbose_name='数据库名称')),
                ('Create_Time', models.DateTimeField(auto_now=True, verbose_name='创建时间（自动获取当前时间）')),
            ],
            options={
                'verbose_name': '环境配置',
                'verbose_name_plural': '环境配置',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, verbose_name='测试用例名称')),
                ('Label', models.CharField(blank=True, max_length=200, verbose_name='测试用例标签')),
                ('FrontSQL', models.CharField(blank=True, max_length=200, verbose_name='前置数据命令')),
                ('ApiPath', models.CharField(max_length=200, verbose_name='接口路径')),
                ('headers', models.CharField(max_length=200, verbose_name='接口头信息')),
                ('RequestMethod', models.CharField(max_length=200, verbose_name='请求方法')),
                ('RequestData', models.TextField(max_length=50000, verbose_name='接口请求体')),
                ('ReponseCheckType', models.CharField(choices=[('FM', '全量匹配'), ('PM', '部分匹配')], max_length=2, verbose_name='验证机制')),
                ('ReponseCheckPoint', models.TextField(max_length=2000, verbose_name='响应体检查点')),
                ('HttpCodeCheck', models.CharField(max_length=200, verbose_name='HTTPCode检查点')),
                ('Create_Time', models.DateTimeField(auto_now=True, verbose_name='创建时间（自动获取当前时间）')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
        migrations.CreateModel(
            name='TestResultsDetail',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TestCase', models.CharField(max_length=200, verbose_name='测试用例名称')),
                ('Result', models.CharField(max_length=200, verbose_name='测试结果')),
                ('Expected_Return_Result', models.CharField(max_length=1000, verbose_name='预计返回结果')),
                ('Actual_Return_Result', models.CharField(max_length=1000, verbose_name='实际返回结果')),
                ('Create_Time', models.DateTimeField(auto_now=True, verbose_name='创建时间（自动获取当前时间）')),
            ],
            options={
                'verbose_name': '测试结果明细',
                'verbose_name_plural': '测试结果明细',
            },
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, verbose_name='测试结果名称')),
                ('Result', models.CharField(max_length=200, verbose_name='测试结果')),
                ('Create_Time', models.DateTimeField(auto_now=True, verbose_name='创建时间（自动获取当前时间）')),
                ('TestResultsDetail', models.ForeignKey(on_delete=True, to='WebServer.TestResultsDetail')),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
            },
        ),
    ]
